# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      # Cancel building pull requests when there aren't changed in the docs directory or Readthedocs config YAML file.
      # If there are no changes (git diff exits with 0) we force the command to return with 183.
      # This is a special exit code on Read the Docs that will cancel the build immediately.
      # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yaml;
        then
          exit 183;
        fi
      # Support Git LFS: Download and uncompress the binary
      # https://docs.readthedocs.io/en/stable/build-customization.html#support-git-lfs-large-file-storage
      - |
        wget https://github.com/git-lfs/git-lfs/releases/download/v3.5.1/git-lfs-linux-amd64-v3.5.1.tar.gz
        if [ $? -eq 0 ]; then
          tar xvfz git-lfs-linux-amd64-v3.5.1.tar.gz
          lfs_dir=$(tar -tf git-lfs-linux-amd64-v3.5.1.tar.gz | head -1 | xargs dirname)
          # Modify LFS config paths to point where git-lfs binary was downloaded
          git config filter.lfs.process "`pwd`/$lfs_dir/git-lfs filter-process"
          git config filter.lfs.smudge  "`pwd`/$lfs_dir/git-lfs smudge -- %f"
          git config filter.lfs.clean "`pwd`/$lfs_dir/git-lfs clean -- %f"
          # Make LFS available in current repository 
          ./$lfs_dir/git-lfs install
          # Download content from remote
          ./$lfs_dir/git-lfs fetch
          # Make local files to have the real content on them
          ./$lfs_dir/git-lfs checkout
        else
          echo "Download of git-lfs failed"
        fi
    

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# Uncomment the following lines to enable PDF generation
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/.sphinx/requirements.txt
