{
 "title": "Testflinger Dashboard",
 "description": "Testflinger Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "API Server Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{juju_application=\"testflinger\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(flask_http_request_duration_seconds_count{status=~\"200|204\"}[$__rate_interval]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{juju_application=\"testflinger\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(flask_http_request_duration_seconds_sum{status=~\"200|204\"}[$__rate_interval])) / sum by(endpoint) (rate(flask_http_request_duration_seconds_count{status=~\"200|204\"}[$__rate_interval]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status) (increase(flask_http_request_total[$__rate_interval]))",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Requests under 250ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(endpoint) (increase(flask_http_request_duration_seconds_bucket{status=~\"200|204\", le=\"0.25\"}[$__rate_interval])) / ignoring(le) sum by(endpoint) (increase(flask_http_request_duration_seconds_count{status=~\"200|204\"}[$__rate_interval]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(flask_http_request_duration_seconds_count{status!~\"200|204\"}[$__rate_interval]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(endpoint) (histogram_quantile(0.5, rate(flask_http_request_duration_seconds_bucket{status=\"200\"}[$__rate_interval])))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(endpoint) (histogram_quantile(0.9, rate(flask_http_request_duration_seconds_bucket{status=~\"200|204\"}[$__rate_interval])))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  { "title": "Testflinger Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Total jobs submitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "sum(testflinger_jobs_total)", "legendFormat": "__auto" }
   ]
  }
 ]
}