issuer: http://dex:5556
storage:
  type: memory
web:
  http: 0.0.0.0:5556
staticClients:
  - id: testflinger-client
    redirectURIs:
      - 'http://testflinger-server:5000/auth/callback'
      - 'http://localhost:5000/auth/callback'
      - 'http://127.0.0.1:5000/auth/callback'
      - '/device/callback'
    name: 'Testflinger Dev'
    public: true
    grantTypes:
enablePasswordDB: true
staticPasswords:
  - email: "testflinger@example.com"
    hash: "$2a$10$FWI.y.8Zpa9PhTTcV6GDIuxPzrwYJoiVCimgCA427HoyR5FR50mBu"
    username: "testflinger-admin"
    userID: "1001"
  - email: "dev-admin@example.com"
    hash: "$2a$10$FWI.y.8Zpa9PhTTcV6GDIuxPzrwYJoiVCimgCA427HoyR5FR50mBu"
    username: "dev-admin"
    userID: "1002"
  - email: "alice@example.com"
    hash: "$2a$10$FWI.y.8Zpa9PhTTcV6GDIuxPzrwYJoiVCimgCA427HoyR5FR50mBu"
    username: "alice"
    userID: "1003"
  - email: "bob@example.com"
    hash: "$2a$10$FWI.y.8Zpa9PhTTcV6GDIuxPzrwYJoiVCimgCA427HoyR5FR50mBu"
    username: "bob"
    userID: "1004"
  - email: "carol@example.com"
    hash: "$2a$10$FWI.y.8Zpa9PhTTcV6GDIuxPzrwYJoiVCimgCA427HoyR5FR50mBu"
    username: "carol"
    userID: "1005"
  - email: "dave@example.com"
    hash: "$2a$10$FWI.y.8Zpa9PhTTcV6GDIuxPzrwYJoiVCimgCA427HoyR5FR50mBu"
    username: "dave"
    userID: "1006"
oauth2:
  grantTypes:
    - "authorization_code"
    - "refresh_token"
    - "urn:ietf:params:oauth:grant-type:device_code"
