# Generated by devel/generate_sample_users.py. Do not edit.
# Copyright (C) 2026 Canonical
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""Generated development auto-sign-in identities."""

DEV_SIGNIN_IDENTITIES = [
    {
        "email": "testflinger@example.com",
        "name": "testflinger-admin",
        "sub": "1001",
        "role": "admin",
        "label": "testflinger-admin (admin)",
    },
    {
        "email": "alice@example.com",
        "name": "alice",
        "sub": "1003",
        "role": "admin",
        "label": "alice (admin)",
    },
    {
        "email": "bob@example.com",
        "name": "bob",
        "sub": "1004",
        "role": "manager",
        "label": "bob (manager)",
    },
    {
        "email": "carol@example.com",
        "name": "carol",
        "sub": "1005",
        "role": "contributor",
        "label": "carol (contributor)",
    },
]
