name: testflinger-cli
title: Testflinger
summary: Testflinger CLI
description: |
  The testflinger-cli tool is used for interacting with the testflinger
  server for submitting test jobs, checking status, getting results, and
  streaming output.
confinement: strict
base: core22
grade: stable
adopt-info: testflinger-cli

website: https://testflinger.readthedocs.io/en/latest/
source-code: https://github.com/canonical/testflinger
issues: https://github.com/canonical/testflinger/issues
contact: https://github.com/canonical/testflinger/issues

architectures:
  - build-on: [amd64]
    build-for: [all]

apps:
  testflinger-cli:
    command: testflinger-cli
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      XDG_DATA_HOME: $SNAP_USER_DATA/.local/share
      XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
      XDG_CACHE_HOME: $SNAP_USER_DATA/.cache
      XDG_STATE_HOME: $SNAP_USER_DATA/.local/state
    plugs:
      - home
      - network

parts:
  launcher:
    plugin: dump
    source: .

  testflinger-cli:
    plugin: python
    source: .
    build-environment:
    - PIP_NO_BINARY: ":all:"
    override-pull: |
      set -e
      craftctl default
      craftctl set version="$(date +%Y%m%d)"
