name: testflinger-cli
title: Testflinger
summary: Testflinger CLI
description: |
  The testflinger-cli tool is used for interacting with the testflinger
  server for submitting test jobs, checking status, getting results, and
  streaming output.
confinement: strict
base: core22
grade: stable
adopt-info: testflinger-cli

website: https://testflinger.readthedocs.io/en/latest/
source-code: https://github.com/canonical/testflinger
issues: https://github.com/canonical/testflinger/issues
contact: https://github.com/canonical/testflinger/issues

architectures:
  - build-on: [amd64]
    build-for: [all]

apps:
  testflinger-cli:
    command: bin/testflinger-cli.wrapper
    plugs:
      - home
      - network

parts:
  launcher:
    plugin: dump
    source: .
    organize:
      testflinger-cli.wrapper: bin/testflinger-cli.wrapper
  testflinger-cli:
    plugin: python
    source: .
    build-environment:
    - PIP_NO_BINARY: ":all:"
    override-pull: |
      set -e
      craftctl default
      craftctl set version="$(date +%Y%m%d)"
