name: testflinger-cli
adopt-info: testflinger-cli
license: GPL-3.0-only
title: Testflinger
summary: Testflinger CLI
description: |
  The testflinger-cli tool is used for interacting with the testflinger
  server for submitting test jobs, checking status, getting results, and
  streaming output.

website: https://testflinger.readthedocs.io/en/latest/
source-code: https://github.com/canonical/testflinger
issues: https://github.com/canonical/testflinger/issues
contact: https://github.com/canonical/testflinger/issues

base: core24
confinement: strict
grade: stable

platforms:
  all:
    build-on: [amd64]
    build-for: [all]

apps:
  testflinger-cli:
    command: bin/testflinger-cli
    completer: testflinger-completion
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      XDG_DATA_HOME: $SNAP_USER_DATA/.local/share
      XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
      XDG_CACHE_HOME: $SNAP_USER_DATA/.cache
      XDG_STATE_HOME: $SNAP_USER_DATA/.local/state
    plugs:
      - home
      - removable-media
      - network

parts:
  testflinger-cli:
    plugin: uv
    source: .
    build-snaps:
      - astral-uv
    build-environment:
      - UV_NO_BINARY: "true"
    override-pull: |
      set -e
      craftctl default
      craftctl set version="$(date +%Y%m%d)"

  completion:
    plugin: dump
    source: .
    stage:
      - testflinger-completion
