name: testflinger-cli
summary: testflinger-cli
description: |
  The testflinger-cli tool is used for interacting with the testflinger
  server for submitting test jobs, checking status, getting results, and
  streaming output.
confinement: strict
base: core22
grade: stable
adopt-info: testflinger-cli

architectures:
  - build-on: [amd64]
    build-for: [all]

plugs:
  dot-config-testflinger-cli:
    interface: personal-files
    read:
      - $HOME/.config/testflinger-cli.conf
  dot-local-share-testflinger-cli-history:
    interface: personal-files
    write:
      - $HOME/.local/share/testflinger-cli-history.json

apps:
  testflinger-cli:
    command: bin/testflinger-cli.wrapper
    plugs:
      - home
      - network
      - dot-config-testflinger-cli
    slots:
      - dot-local-share-testflinger-cli-history

parts:
  launcher:
    plugin: dump
    source: .
    organize:
      testflinger-cli.wrapper: bin/testflinger-cli.wrapper
  testflinger-cli:
    plugin: python
    source: .
    build-environment:
    - PIP_NO_BINARY: ":all:"
    override-pull: |
      set -e
      craftctl default
      craftctl set version="$(date +%Y%m%d)"
