[tox]
env_list =
    format
    lint
    unit
requires =
    tox-uv
skipsdist = true

[testenv]
runner = uv-venv-lock-runner
set_env =
    HOME = {envtmpdir}

[testenv:format]
commands =
    black --check testflinger_cli

[testenv:lint]
commands =
    flake8 testflinger_cli
    pylint testflinger_cli

[testenv:unit]
commands =
    pytest --doctest-modules --cov=.
