name: Submit a Testflinger job
description: Submit a job to a Testflinger server
inputs:
  job:
    description: "Inline contents of a job file (see https://canonical-testflinger.readthedocs-hosted.com/en/latest/reference/job-schema/ for more info)"
    required: false
  job-path:
    description: "Path to a job file (see https://canonical-testflinger.readthedocs-hosted.com/en/latest/reference/job-schema/ for more info)"
    required: false
  poll:
    description: Specify if the submitted job should be tracked to completion
    required: false
    default: "false"
  dry-run:
    description: Specify if the job should really be submitted
    required: false
    default: "false"
  server:
    description: The Testflinger server to use
    required: false
    default: testflinger.canonical.com
  attachments-relative-to:
    description: The reference directory for relative attachment paths
    required: false
  client-id:
    description: Client ID for jobs requiring authentication
    required: false
  secret-key:
    description: Secret key for jobs requiring authentication
    required: false
outputs:
  id:
    description: 'The ID of the submitted job'
    value: ${{ steps.submit.outputs.id }}
  device-ip:
    description: 'The IP of the reserved device (if applicable)'
    value: ${{ steps.track-reservation.outputs.ip }}
runs:
  using: composite
  steps:
    - name: Set up Testflinger
      uses: ./.github/actions/testflinger-setup
      with:
        server: ${{ inputs.server }}

    - name: Create job file, if required
      id: create-job-file
      shell: bash
      env:
        JOB: ${{ inputs.job }}
        JOB_PATH: ${{ inputs.job-path }}
        WORKSPACE: ${{ github.workspace }}
      run: |
        echo "::group::Create job file (if required)"
        if [ -n "$JOB_PATH" ]; then
          echo "job=$JOB_PATH" >> "$GITHUB_OUTPUT"
        else
          # write the inline job text to a file
          FILE=$WORKSPACE/tmp_job.yaml
          printf "%s" "$JOB" > "$FILE"
          if [[ $(cat "$FILE" | wc -w) == 0 ]]; then
            echo 'Neither of the `job` or `job-path` inputs have been specified'
            exit 1
          fi
          echo "job=$FILE" >> "$GITHUB_OUTPUT"
        fi
        echo "::endgroup::"

    - name: Display contents of job file (for verification)
      shell: bash
      env:
        JOB: ${{ steps.create-job-file.outputs.job }}
      run: |
        echo "::group::Display job file"
        cat "$JOB"
        echo "::endgroup::"

    - name: Determine if this is a reservation job
      id: check-reservation
      shell: bash
      env:
        JOB: ${{ steps.create-job-file.outputs.job }}
      run: |
        echo "::group::Determine if this is a reservation job"
        if grep -q "^reserve_data:" "$JOB"; then
          RESERVATION=true
        else
          RESERVATION=false
        fi
        echo "reservation=$RESERVATION" | tee -a $GITHUB_OUTPUT
        echo "::endgroup::"

    - name: Submit job to the Testflinger server
      id: submit
      if: inputs.dry-run != 'true'
      shell: bash
      env:
        SERVER: https://${{ inputs.server }}
        RELATIVE_TO: ${{ inputs.attachments-relative-to }}
        CLIENT_ID: ${{ inputs.client-id }}
        SECRET_KEY: ${{ inputs.secret-key }}
        JOB: ${{ steps.create-job-file.outputs.job }}
      run: |
        echo "::group::Submit job to the Testflinger server"
        AUTH_ARGS_COUNT=0
        [[ -n $CLIENT_ID ]] && ((++AUTH_ARGS_COUNT))
        [[ -n $SECRET_KEY ]] && ((++AUTH_ARGS_COUNT))
        case $AUTH_ARGS_COUNT in
            0) AUTH_ARGS=() ;;
            2) AUTH_ARGS=( --client_id "$CLIENT_ID" --secret_key "$SECRET_KEY" ) ;;
            1) echo "::error::Both 'client-id' and 'secret-key' must be provided or neither"; exit 1 ;;
        esac
        JOB_ID=$(\
          testflinger --server "$SERVER" submit --quiet \
          ${RELATIVE_TO:+--attachments-relative-to "$RELATIVE_TO"} \
          "${AUTH_ARGS[@]}" \
          "$JOB" \
        )
        echo "id=$JOB_ID" >> $GITHUB_OUTPUT
        echo "::endgroup::"
        echo "::notice::Testflinger job id: $JOB_ID"

    - name: Track the status of the job (non-reservation)
      if: inputs.poll == 'true' && inputs.dry-run != 'true' && steps.check-reservation.outputs.reservation != 'true'
      shell: bash
      env:
        SERVER: https://${{ inputs.server }}
        JOB_ID: ${{ steps.submit.outputs.id }}
      run: |
        echo "::group::Track the status of job $JOB_ID"
        # poll
        PYTHONUNBUFFERED=1 testflinger --server $SERVER poll $JOB_ID
        echo "::endgroup::"
        
        echo "::group::Retrieve job results, determine exit status"
        # the exit status is the maximum status of the individual test phases
        # (excluding the setup and cleanup phases)
        read PHASE EXIT_STATUS <<< $(\
          testflinger --server "$SERVER" results "$JOB_ID"  \
          | jq -r 'to_entries
            | map(
              select(
                (.key | endswith("_status"))
                and .key != "setup_status"
                and .key != "cleanup_status"
              )
            )
          | max_by(.value) | [.[]] | join(" ")'
        )
        [[ $EXIT_STATUS -ne 0 ]] && echo "::error::Testflinger ${PHASE%_status} phase failed"
        echo "::endgroup::"
        exit $EXIT_STATUS

    - name: Track the status of the job (reservation)
      id: track-reservation
      if: inputs.poll == 'true' && inputs.dry-run != 'true' && steps.check-reservation.outputs.reservation == 'true'
      shell: bash
      env:
        SERVER: https://${{ inputs.server }}
        JOB_ID: ${{ steps.submit.outputs.id }}
        TERMINATION: "TESTFLINGER SYSTEM RESERVED"
      run: |
        echo "::group::Track the status of reservation job $JOB_ID"
        # specify file for capturing output and clear it
        CAPTURED_OUTPUT=output
        > "$CAPTURED_OUTPUT"
        # perform one-shot polling until the reserve phase has been reached
        # and the captured output contains the TERMINATION string
        while true; do
          PYTHONUNBUFFERED=1 testflinger --server $SERVER poll --oneshot $JOB_ID | tee -a "$CAPTURED_OUTPUT"
          JOB_STATUS="$(testflinger --server $SERVER status $JOB_ID)"
          if [ "$JOB_STATUS" = "reserve" ]; then
            if grep -q "$TERMINATION" "$CAPTURED_OUTPUT"; then
              EXIT_STATUS=0
              break
            fi
          elif [[ "$JOB_STATUS" =~ ^(complete|cancelled)$ ]]; then
            EXIT_STATUS=1
            break
          fi
          sleep 10
        done
        echo "::endgroup::"
        echo "::group::Retrieve IP of reserved machine"
        DEVICE_IP=$(grep -m 1 "^You can now connect to" "$CAPTURED_OUTPUT" | sed -n "s/.*@\([0-9.]*\).*/\1/p")
        [ "$?" -eq 0 ] && DEVICE_IP_FLAG=true
        [ -n "$DEVICE_IP_FLAG" ] && echo "ip=$DEVICE_IP" >> $GITHUB_OUTPUT
        echo "::endgroup::"
        [ $EXIT_STATUS -ne 0 ] && echo "::error::Testflinger reservation phase failed"
        [ -n "$DEVICE_IP_FLAG" ] && echo "::notice::Device IP: $DEVICE_IP"
        exit $EXIT_STATUS

    - name: Cancel the job if the action is cancelled
      if: ${{ cancelled() }}
      shell: bash
      env:
        SERVER: https://${{ inputs.server }}
        JOB_ID: ${{ steps.submit.outputs.id }}
      run: |
        echo "::group::Cancel job"
        testflinger --server $SERVER cancel $JOB_ID
        echo "::endgroup::"
