name: Setup Testflinger
description: "Configure runner environment with network settings and CLI installation"
inputs:
  server:
    description: The Testflinger server to use
    required: false
    default: testflinger.canonical.com

runs:
  using: composite
  steps:
    - name: Test connection to Testflinger server
      shell: bash {0}  # allow curl to fail
      env:
        SERVER: https://${{ inputs.server }}
        REQUEST_ID: ${{ github.run_id }}
      run: |
        echo "::group::Test connection to Testflinger server"
        STATUS=$(curl --stderr error.log -Ivw "%{http_code}\n" -o /dev/null $SERVER/v1/ -H "X-Request-ID: $REQUEST_ID")
        ERROR=$?
        if [ ! $ERROR -eq 0 ]; then
          echo "Unable to ping Testflinger server at $SERVER"
          cat error.log
          exit $ERROR
        elif [ ! $STATUS -eq 200 ]; then
          echo "Failed server ping at $SERVER, error status: $STATUS"
          cat error.log
          exit $STATUS
        else
          echo "Successful server ping at $SERVER, status: $STATUS"
        fi
        echo "::endgroup::"

    - name: Install CLI prerequisites
      shell: bash
      run: |
        echo "::group::Install prerequisites"
        sudo snap install testflinger-cli
        # Prefer jq apt package as the snap is extremely out of date
        sudo apt-get install -y jq
        sudo snap install yq
        echo "::endgroup::"
