[tox]
env_list =
    lock
    format
    lint
    unit
    schema
no_package = true
requires =
    tox-uv>=1.25.0

[testenv]
runner = uv-venv-lock-runner
dependency_groups = 
    dev

[testenv:lock]
description = Check lock file
commands = 
    uv lock --check

[testenv:format]
description = Apply coding style standards to code
commands =
    djlint --reformat src
    ruff format
    ruff check --fix

[testenv:lint]
description = Check code against coding style standards
pass_env = RUFF_*
commands =
    djlint --check src
    djlint --lint src
    ruff format --check
    # keep ruff check last so that it generates the last `results.sarif` file
    # in the GH workflows
    ruff check

[testenv:unit]
description = Run unit tests
commands =
    pytest \
        --ignore app.py \
        --cov=src \
        --cov-branch \
        --cov-report=term \
        --cov-report=xml:coverage.xml \
        {posargs:tests}

[testenv:schema]
description = Generate server OpenAPI schema
commands =
    python scripts/generate_openapi_schema.py --output schemas/openapi.json

[testenv:check-schema]
description = Check server OpenAPI schema is up-to-date
commands =
    python scripts/generate_openapi_schema.py --diff schemas/openapi.json
