options:
  external_hostname:
    default: testflinger.local
    description: external hostname for accessing testflinger server
    type: string
  keepalive:
    default: 10
    description: Number of seconds to wait for keepalive connections
    type: int
  max_pool_size:
    default: 100
    description: Maximum number of concurrent connections to the database
    type: int
  jwt_signing_key:
    default: ""
    description: Secret key used for signing authorization tokens
    type: string
