build: fetch-libs
	charmcraft pack

fetch-libs:
	 charmcraft fetch-lib charms.data_platform_libs.v0.data_interfaces
	 charmcraft fetch-lib charms.nginx_ingress_integrator.v0.nginx_route
	 charmcraft fetch-lib charms.prometheus_k8s.v0.prometheus_scrape
	 charmcraft fetch-lib charms.observability_libs.v0.juju_topology
