#!/usr/bin/env python3
# Copyright (C) 2026 Canonical
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
Generate or validate the API role-permission matrix for Testflinger docs.

This script derives the permissions matrix from the OpenAPI spec produced by
generate_openapi_schema.py, which already annotates each operation with
`x-permission-roles` (sourced from the `@require_role` decorator).

The output is an RST fragment meant to be pulled into
docs/reference/api-roles.rst via `.. include::`.

Usage:

Activate the server virtualenv first (uv sync && source .venv/bin/activate)
or use the project uvx runner so imports and deps are available.

    # Generate the matrix table to stdout
    python generate_api_roles.py

    # Write the matrix table to file
    python generate_api_roles.py -o ../docs/reference/api-roles-table.txt

    # Check if the committed table matches current API
    python generate_api_roles.py -d ../docs/reference/api-roles-table.txt
"""

import argparse
import sys
import textwrap
from pathlib import Path

from generate_openapi_schema import generate_schema
from testflinger_common.enums import ServerRoles

# Allowing a role implies allowing every more-privileged role.
# AGENT is a separate machine role outside this hierarchy.
HUMAN_ROLE_HIERARCHY = (
    ServerRoles.CONTRIBUTOR,
    ServerRoles.MANAGER,
    ServerRoles.ADMIN,
)

# Display columns: AGENT first, then the human hierarchy.
ROLE_DISPLAY_ORDER = (ServerRoles.AGENT, *HUMAN_ROLE_HIERARCHY)

GENERATED_FILE_NOTICE = (
    ".. Generated by `python scripts/generate_api_roles.py`; do not edit "
    "by hand."
)


def _iter_spec_operations(spec: dict):
    """Yield (method, path, operation) for every operation in an OpenAPI spec."""
    for path, path_item in spec.get("paths", {}).items():
        if not isinstance(path_item, dict):
            continue
        for method in ("get", "post", "put", "patch", "delete"):
            operation = path_item.get(method)
            if isinstance(operation, dict):
                yield method, path, operation


def _role_cell(role: ServerRoles, allowed_roles: list) -> str:
    """Render one role-matrix cell as an allowed/restricted octicon marker."""
    if role.value in allowed_roles:
        return ":octicon:`check-circle-fill;1em;sd-text-success` :vh:`allowed`"
    return ":octicon:`x-circle-fill;1em;sd-text-danger` :vh:`restricted`"


def _render_list_table_row(cells: list) -> list:
    """Render one `* - ...` list-table row, wrapping long cell text."""
    lines = []
    for index, cell in enumerate(cells):
        prefix = "   * - " if index == 0 else "     - "
        wrapped = textwrap.wrap(cell, width=68) or [""]
        lines.append(f"{prefix}{wrapped[0]}")
        lines.extend(f"       {extra}" for extra in wrapped[1:])
    return lines


def _validate_role_hierarchy(method: str, path: str, allowed: set) -> None:
    """Fail if human-role access for an endpoint is not upward-closed.

    Allowing a lower human role while denying a higher one contradicts the
    role hierarchy (a MANAGER should have at least a CONTRIBUTOR's access),
    so it almost certainly signals a mistaken `@require_role` decorator
    rather than an intended permission set.
    """
    for lower, higher in zip(HUMAN_ROLE_HIERARCHY, HUMAN_ROLE_HIERARCHY[1:]):
        if lower in allowed and higher not in allowed:
            hierarchy = " < ".join(r.value for r in HUMAN_ROLE_HIERARCHY)
            raise ValueError(
                f"{method.upper()} {path} allows '{lower.value}' but not "
                f"'{higher.value}'. Human-role access must be upward-closed "
                f"({hierarchy}); a more-privileged role should never have "
                "less access. Fix the @require_role decorator."
            )


def _role_group_key(method: str, path: str, roles: list) -> tuple:
    """Sort key that clusters rows by their (validated) role set.

    The order of role set is described by two dimensions:
    - whether AGENT is allowed,
    - whether the lowest (widest-audience) human role is allowed. 
    
    This groups identical role sets together and keeps a semantic ordering.
    """
    allowed = {ServerRoles(role) for role in roles}
    _validate_role_hierarchy(method, path, allowed)
    agent_first = ServerRoles.AGENT not in allowed
    human_tier = next(
        (i for i, r in enumerate(HUMAN_ROLE_HIERARCHY) if r in allowed),
        len(HUMAN_ROLE_HIERARCHY),
    )
    # Mirror the tier for agent rows so the two sections form a gradient.
    return (agent_first, human_tier if agent_first else -human_tier)


def generate_roles_matrix(spec: dict) -> str:
    """Render the "Endpoint permissions by role" list-table from an OpenAPI spec."""
    matrix_rows = [
        (method, path, roles)
        for method, path, operation in _iter_spec_operations(spec)
        if (roles := operation.get("x-permission-roles"))
    ]
    # Cluster by role set; order by path within each cluster.
    matrix_rows.sort(key=lambda row: (_role_group_key(*row), row[1]))

    lines = [GENERATED_FILE_NOTICE, ""]
    lines.append(".. rst-class:: api-roles-table")
    lines.append(".. list-table:: Endpoint permissions by role")
    lines.append("   :header-rows: 1")
    lines.append("   :widths: 8 36 10 13 10 8")
    lines.append("")
    lines.extend(
        _render_list_table_row(
            ["Method", "URI"] + [role.name for role in ROLE_DISPLAY_ORDER]
        )
    )
    for method, path, roles in matrix_rows:
        cells = [f"``{method.upper()}``", f"``{path}``"]
        cells.extend(_role_cell(role, roles) for role in ROLE_DISPLAY_ORDER)
        lines.extend(_render_list_table_row(cells))

    return "\n".join(lines) + "\n"


def diff_roles_matrix(local_path: Path) -> bool:
    """
    Generate the API roles matrix from code and compare with the committed
    include fragment.

    Args:
        local_path: Path to the expected RST include fragment

    Returns:
        True if the fragment is up to date, False otherwise
    """
    generated = generate_roles_matrix(generate_schema())

    if not local_path.exists():
        print(
            f"Error: Expected roles matrix file not found: {local_path}",
            file=sys.stderr,
        )
        return False

    local = local_path.read_text()

    if generated != local:
        print("Error: API roles matrix is out of date", file=sys.stderr)
        print("", file=sys.stderr)
        print(
            "To update the matrix, run from server/ directory:",
            file=sys.stderr,
        )
        print("  uvx --with tox-uv tox run -e roles-docs", file=sys.stderr)
        return False

    return True


def main():
    """Generate or validate the API role-permission matrix."""
    parser = argparse.ArgumentParser(
        description=(
            "Generate or validate the API role-permission matrix for "
            "Testflinger server docs"
        )
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=None,
        help="Write matrix to specified file (default is stdout)",
    )
    parser.add_argument(
        "--diff",
        "-d",
        type=Path,
        help="Compare generated matrix with the specified file for validation",
    )

    args = parser.parse_args()

    if args.diff:
        if not diff_roles_matrix(args.diff):
            sys.exit(1)
        print(" API roles matrix is up to date")
        sys.exit(0)

    if args.output:
        matrix = generate_roles_matrix(generate_schema())
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(matrix)
        print(f" API roles matrix written to: {args.output}")
    else:
        print(generate_roles_matrix(generate_schema()))


if __name__ == "__main__":
    main()
