#!/usr/bin/env python3

# Copyright (C) 2015 Canonical
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import argparse
import os
import subprocess
import tempfile

import constants


def parse_args():
        parser = argparse.ArgumentParser()
        parser.add_argument('-u', '--test-url', required=True,
                            help='URL of the test tarball')
        args = parser.parse_args()
        return args


def main():
    args = parse_args()
    with tempfile.TemporaryDirectory() as tmpdir:
        filename = os.path.split(args.test_url)[1]
        testdir = os.path.join(tmpdir, 'test')
        # XXX: Agent should pass us the output location
        outputdir = '/tmp/output'

        subprocess.check_output(['wget', args.test_url], cwd=tmpdir)
        os.makedirs(testdir)
        # Extraction directory does not get renamed, and test_cmd
        # gets run from one level above
        subprocess.check_output(['tar', '-xf', filename, '-C', testdir,
                                 '--strip-components=1'], cwd=tmpdir)
        test_cmd = ['adt-run', '--built-tree', testdir, '--output-dir',
                    outputdir, '---', 'ssh', '-d', '-l', 'ubuntu', '-P',
                    'ubuntu', '-H', constants.TEST_HOST]
        subprocess.check_output(test_cmd, cwd=tmpdir)


if __name__ == '__main__':
    main()
