#!/bin/bash

AGENT=$(echo $agent_id | sed 's/-\([0-9]*\)$/\1/g')
PROVISION_TYPE="$provision_type"

# The following variables are set by the agent charm
AGENT_CONFIGS_PATH={{ agent_configs_path }}
CONFIG_DIR="{{ config_dir }}"
VIRTUAL_ENV_PATH="{{ virtual_env_path }}"
REAL_VENV_PATH=$(readlink -f "$VIRTUAL_ENV_PATH")

if [ -d "$VIRTUAL_ENV_PATH" ]; then
    PYTHONUNBUFFERED=1 flock -s "$REAL_VENV_PATH/.venv.lock" "$REAL_VENV_PATH/bin/testflinger-device-connector" $PROVISION_TYPE provision -c $AGENT_CONFIGS_PATH/$CONFIG_DIR/$agent_id/default.yaml testflinger.json
else
    . /srv/testflinger-agent/$AGENT/env/bin/activate && PYTHONUNBUFFERED=1 testflinger-device-connector $PROVISION_TYPE provision -c /srv/testflinger-agent/$AGENT/default.yaml testflinger.json
fi
