#!/bin/bash

AGENT=$(echo $agent_id | sed 's/-\([0-9]*\)$/\1/g')
PROVISION_TYPE="$provision_type"
VIRTUAL_ENV_PATH="{{ virtual_env_path }}"

if [ -d "$VIRTUAL_ENV_PATH" ]; then
    echo Cleaning up container if it exists... && docker rm -f $agent_id 2> /dev/null || /bin/true
else
    echo Cleaning up container if it exists... && docker rm -f $AGENT 2> /dev/null || /bin/true
fi

