options:
  testflinger-repo:
    type: string
    description: git repo for testflinger
    default: "https://github.com/canonical/testflinger"
  testflinger-branch:
    type: string
    description: git branch for testflinger
    default: "main"

