[tox]
env_list =
    lock
    format
    lint
    unit
no_package = true
requires =
    tox-uv>=1.25.0


[vars]
src_path = {tox_root}/src
tests_path = {tox_root}/tests
all_path = {[vars]src_path} {[vars]tests_path}

[testenv]
runner = uv-venv-lock-runner
set_env =
    PYTHONPATH = {tox_root}/lib:{[vars]src_path}
pass_env =
    PYTHONPATH

[testenv:lock]
description = Check lock file
commands = 
    uv lock --check

[testenv:format]
description = Apply coding style standards to code
dependency_groups =
    lint
    unit
    integration
commands =
    ruff format {[vars]all_path}
    ruff check --fix {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards
dependency_groups =
    lint
    unit
    integration
commands =
    ruff check {[vars]all_path}
    ruff format --check --diff {[vars]all_path}

[testenv:unit]
description = Run unit tests
dependency_groups =
    unit
commands =
    coverage run --source={[vars]src_path} \
                 -m pytest \
                 --tb native \
                 -v \
                 -s \
                 {[vars]tests_path}/unit \
                 {posargs}
    coverage report
    coverage xml


[testenv:integration]
description = Run integration tests
dependency_groups =
    integration
commands =
    pytest -v \
           -s \
           --tb native \
           --log-cli-level=INFO \
           {[vars]tests_path}/integration \
           {posargs}
