name: "[agent] Release testflinger-agent-host charm"
run-name: "[agent] Release testflinger-agent-host charm (${{ github.event_name == 'push' && 'beta' || github.event.inputs.channel }})"
permissions:
  contents: read
on:
  push:
    branches: [main]
    paths:
      - agent/charms/testflinger-agent-host-charm/**
      - .github/workflows/agent-host-charm-release.yml
  workflow_dispatch:
    inputs:
      channel:
        description: The channel to release the charm to
        required: true
        default: latest/edge
        type: choice
        options:
          - latest/beta
          - latest/edge

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  agent-build-and-push-charm:
    name: Build and Push Charm
    runs-on: [self-hosted, linux, jammy, X64]
    permissions:
      actions: read  # necessary to get the runner information
      contents: write  # necessary to create tag(s)
      packages: write  # necessary to upload image

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          persist-credentials: false
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@1753e0803f70445132e92acd45c905aba6473225 # 2.7.0
        with:
          charm-path: agent/charms/testflinger-agent-host-charm
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: ${{ github.event_name == 'push' && 'latest/beta' || github.event.inputs.channel }}
          tag-prefix: "agent-host-charm"

  scan:
    needs: agent-build-and-push-charm
    name: Scan Charm with Trivy
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    env:
      CHANNEL: ${{ github.event_name == 'push' && 'beta' || github.event_name == 'schedule' && 'stable' || github.event.inputs.channel }}
    steps:
      - name: Install Juju
        run: sudo snap install juju --classic
      - name: Download and Unpack Charm
        run: |
          CHANNEL=$(echo "$CHANNEL" | sed "-e s,latest/,,")
          CHARM=$(juju download testflinger-agent-host --channel=$CHANNEL 2>&1 | grep ".charm$" | sed -e 's/.*\(testflinger.*.charm\)/\1/')

          # Extract the contents to a local folder
          unzip -d unpacked-charm $CHARM
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: 'fs'
          scan-ref: 'unpacked-charm'
          exit-code: 1
          format: 'sarif'
          vuln-type: library
          output: 'testflinger-agent-host-trivy-results.sarif'
          # By default, SARIF format enforces output of all vulnerabilities regardless of configured severities.
          severity: 'UNKNOWN,LOW,MEDIUM,CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4.32.6
        with:
          sarif_file: 'testflinger-agent-host-trivy-results.sarif'
          wait-for-processing: "true"