name: Promote testflinger-agent-host charm from edge to latest/stable

on:
  workflow_dispatch:

jobs:
  promote-charm:
    name: Promote testflinger-agent-host charm to stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release testflinger-agent-host charm to stable
        uses: canonical/charming-actions/promote-charm@main
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          destination-channel: latest/stable
          origin-channel: latest/edge
          charm-path: agent/charms/testflinger-agent-host-charm
