name: Check Agent Host Charm Libs on Pull Request
permissions:
  contents: read
on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/agent-host-charm-check-libs.yml
      - agent/charms/testflinger-agent-host-charm/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Check charm libraries
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # necessary to add label
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Check libraries
        uses: canonical/charming-actions/check-libraries@1753e0803f70445132e92acd45c905aba6473225 # 2.7.0
        with:
          charm-path: agent/charms/testflinger-agent-host-charm
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          charmcraft-channel: latest/stable
