name: cla-check
permissions:
  contents: read
on: [pull_request]

jobs:
  cla-check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@5d1443b94417bd150ad234a82fe21f7340a25e4d # v2
