name: "[cli] Run unit tests"
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/cli-tox.yml
      - cli/**
      - codecov.yaml
  pull_request:
    paths:
      - .github/workflows/cli-tox.yml
      - cli/**
      - codecov.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run unit tests
    defaults:
      run:
        working-directory: cli
    runs-on: ubuntu-latest
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - run: sudo snap install --classic just
      - run: just check-lock
      - run: just lint
        env:
          RUFF_OUTPUT_FORMAT: sarif
          RUFF_OUTPUT_FILE: results.sarif
      - run: just test
      - name: Upload coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: coverage.xml
          flags: cli
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: results.sarif
          path: cli/results.sarif
      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
        with:
          sarif_file: cli/results.sarif
