name: "[cli] Build Testflinger CLI"
run-name: "[cli] Build Testflinger CLI (${{ github.event_name == 'push' && 'latest/beta' || github.event.inputs.release || 'just built' }})"
permissions:
  contents: read
on:
  pull_request:
    paths:
      - cli/**
      - .github/workflows/cli-publish-snap.yml
  push:
#    branches: ["main"]
    paths:
      - cli/**
      - .github/workflows/cli-publish-snap.yml
  workflow_dispatch:
    inputs:
      publish:
        description: Publish the snap to the store
        required: false
        default: false
        type: boolean
      release:
        description: The release channel to publish to
        required: false
        default: edge
        type: choice
        options:
          - beta
          - edge

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  snap:
    name: Build, [Publish,] and Scan Snap

    # At this time, `self-hosted-linux-arm64-jammy-large` are all in PS6 which is able to reach the security scanner
    runs-on: self-hosted-linux-arm64-jammy-large

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          persist-credentials: false
      - name: Build snap
        id: build
        uses: snapcore/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79 # v1
        with:
          path: cli
      - name: Upload snapcraft logs
        if: failure()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: runtime-build-log
          path: |
            /home/runner/.cache/snapcraft/log/
            /home/runner/.local/state/snapcraft/log/
      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: testflinger-cli.snap
          path: ${{ steps.build.outputs.snap }}
      - name: Publish snap
        if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' && github.event.inputs.publish == 'true' }}
        uses: snapcore/action-publish@214b86e5ca036ead1668c79afb81e550e6c54d40 # v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: ${{ github.event_name == 'push' && 'beta' || github.event.inputs.release }}

      - name: Install canonical-secscan-client
        run: |
          sudo snap install canonical-secscan-client

      - name: Run Trivy scan
        env:
          # Use the released snap if just published, else use the local file for scanning
          SNAP: >-
            ${{ 
              ((github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' && github.event.inputs.publish == 'true') && 
                format('testflinger-cli/{0}', github.event.inputs.release))
              || (github.event_name == 'push' && 'testflinger-cli/latest/beta')
              || steps.build.outputs.snap
            }}
        run: |          
          secscan-client submit \
            --wait-and-print \
            --scanner trivy \
            --type package \
            --format snap \
            $SNAP \
            2>&1 | tee trivy-report.json && exit 0

      - name: Run BlackDuck scan
        run: |
          secscan-client submit \
            --wait-and-print \
            --scanner blackduck \
            --type package \
            --format snap \
            $SNAP \
            2>&1 | tee blackduck-report.json && exit 0

      - name: Upload scan reports
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: cli_snap-secscan-reports
          retention-days: 5
          path: |
            trivy-report.json
            blackduck-report.json

      - name: Evaluate scan reports
        run: |
          # Use the released snap if just published, else use the local file for scanning
          echo "WORKFLOW_SNAP = '$WORKFLOW_SNAP'"
          echo "PUSH_SNAP = '$PUSH_SNAP'"
          echo "PR_SNAP = '$PR_SNAP'"
          echo "SNAP = '$SNAP'"
          date
          cat trivy-report.json blackduck-report.json | sort -u | grep "CVE\|Failed\|error" && exit 1 || echo "No CVEs found"
