name: "[common] Run unit tests"
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/common-tox.yml
      - common/**
      - codecov.yaml
  pull_request:
    paths:
      - .github/workflows/common-tox.yml
      - common/**
      - codecov.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run unit tests
    defaults:
      run:
        working-directory: common
    runs-on: ubuntu-latest
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - name: Install uv and set up Python
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Check lock file
        run: uvx --with tox-uv tox -e lock
      - name: Check linting
        env:
          RUFF_OUTPUT_FORMAT: sarif
          RUFF_OUTPUT_FILE: results.sarif
        run: uvx --with tox-uv tox -e lint
      - name: Run unit tests
        run: uvx --with tox-uv tox -e unit

      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: results.sarif
          path: common/results.sarif

      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4.35.4
        with:
          sarif_file: common/results.sarif
