name: "[common] Run unit tests"
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/common-tox.yml
      - common/**
      - codecov.yaml
  pull_request:
    paths:
      - .github/workflows/common-tox.yml
      - common/**
      - codecov.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run unit tests
    defaults:
      run:
        working-directory: common
    runs-on: ubuntu-latest
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install uv and set up Python
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - run: sudo snap install --classic just
      - run: just check-lock
      - run: just lint
        env:
          RUFF_OUTPUT_FORMAT: sarif
          RUFF_OUTPUT_FILE: results.sarif
      - run: just test
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: results.sarif
          path: common/results.sarif
      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          sarif_file: common/results.sarif
