name: "[device-connectors] Run unit tests"
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/device-tox.yml
      - device-connectors/**
      - codecov.yaml
  pull_request:
    paths:
      - .github/workflows/device-tox.yml
      - device-connectors/**
      - codecov.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run unit tests
    defaults:
      run:
        working-directory: device-connectors
    runs-on: ubuntu-latest
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install uv and set up Python
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - run: sudo snap install --classic just
      - run: just check-lock
      - run: just lint
        env:
          RUFF_OUTPUT_FORMAT: sarif
          RUFF_OUTPUT_FILE: results.sarif
      - run: just test
      - name: Upload coverage
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          files: coverage.xml
          flags: device
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: results.sarif
          path: device-connectors/results.sarif
      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4.35.4
        with:
          sarif_file: device-connectors/results.sarif
