name: Update Version File in PR
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/actions/submit/action.yaml

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          # This checks out the PR branch, not main
          ref: ${{ github.event.pull_request.head.ref }}
          #token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Generate semantic version
        id: version
        uses: PaulHatch/semantic-version@v5.4.0
        with:          
          namespace: "submit"
          change_path: ".github/actions/submit/action.yaml"
          major_pattern: "breaking(submit):"
          minor_pattern: "feat(submit):"

      - name: Update version file
        if: steps.version.outputs.changed == 'true'
        env:
            VERSION: ${{ steps.version.outputs.version_tag }}
        run: |
          mkdir -p .github/actions/submit
          echo "$VERSION" > .github/actions/submit/version
          echo ::notice::$VERSION

      - name: Commit and push changes
        if: steps.version.outputs.changed == 'true'
        run: |
          git add .github/actions/submit/version
          if ! git diff --quiet --staged .github/actions/submit/version; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Auto-update version file"
            git push
          fi
